nomad:
  use_prod: false
  dataset:
    id: "HJdEI1q4SV-c5Di43BTT_Q"
  coauthors:
    - "7c85bdf1-8b53-40a8-81a4-04f26ff56f29" # Joe Rudzinski


solute_generation:
  itp_files:
    particle_definition: "../../../martini_v300/martini_v3.0.0.itp"
  mdp_files:
    minimize: "../../../martini_solute_gen/mdp_files/min.mdp"
  settings:
    n_threads: 1
  output_names:
    system: "solute"
    nomad_workflow: "solute_generation.archive.yaml"
    states:
      generate: "gen_mol"
      minimize: "min"
  parameters:
    bond_length: 0.360
    bond_constant: 100000
    number_excl: 3

solvent_generation:
  itp_files:
    - "../../../martini_v300/martini_v3.0.0.itp"
    - "../../../martini_v300/martini_v3.0.0_solvents_v1.itp"
  mdp_files:
    minimize: "../../../martini_solvent_gen/mdp_files/min.mdp"
    equilibrate: "../../../martini_solvent_gen/mdp_files/equ.mdp"
    production: "../../../martini_solvent_gen/mdp_files/run.mdp"
  settings:
    n_threads: 1
    box_length: 5.0
  output_names:
    system: "solvent"
    nomad_workflow: "solvent_generation.archive.yaml"
    states:
      mol: "gen_mol"
      box: "gen_box"
      min: "min"
      equ: "equ"
      prod: "prod"

solute_solvation:
  settings:
    n_threads: 1
  mdp_files:
    minimize: "../../../martini_solvate/mdp_files/min.mdp"
    equilibrate: "../../../martini_solvate/mdp_files/equ.mdp"
  output_names:
    system: "solute_solvent"
    nomad_workflow: "solute_solvation.archive.yaml"
    nomad_top_level_workflow: "full_workflow.solute_solvation.archive.yaml"
    states:
      generate: "gen"
      minimize: "min"
      equilibrate: "equ"

alchemical_transformation:
  settings:
    n_threads: 2
    temperature: 300.
  mdp_files:
    run: "../../../martini_fep/mdp_files/run_lambda.mdp"
  output_names:
    system: "fep"
    nomad_workflow: "alchemical_transformation.archive.yaml"
    nomad_top_level_workflow: "full_workflow.alchemical_transformation.archive.yaml"
    states:
      run: "run"

bilayer_generation:
  itp_files:
    - "../../../martini_v300/martini_v3.0.0.itp"
    - "../../../martini_v300/martini_v3.0.0_solvents_v1.itp"
    - "../../../martini_v300/martini_v3.0.0_phospholipids_v1.itp"
  mdp_files:
    minimize: "../../../martini_bilayers/mdp_files/min.mdp"
    equilibrate: "../../../martini_bilayers/mdp_files/equ.mdp"
  settings:
    n_threads: 1
    box_length_xy: 10
    box_length_z: 7
    solvent:
      -
        name: W
        fraction: 1.0
  output_names:
    system: "bilayer"
    states:
      generate: "gen"
      minimize: "min"
      equilibrate: "equ"