nomad:
  use_prod: false
  dataset:
    id: "HJdEI1q4SV-c5Di43BTT_Q"
  coauthors:
    - "7c85bdf1-8b53-40a8-81a4-04f26ff56f29" # Joe Rudzinski

local:
  workspaces:
    absolute_path: "/Users/bereau/work/projects/martignac/workspaces"
  input_files:
    absolute_path: "/Users/bereau/work/projects/martignac/scripts"

solute_generation:
  relative_paths:
    workspaces: "solute_generation"
    itp_files: "martini_v300"
    mdp_files: "solute_generation/mdp_files"
  itp_files:
    particle_definition: "martini_v3.0.0.itp"
  mdp_files:
    minimize: "min.mdp"
    equilibrate: "equ.mdp"
  settings:
    n_threads: 1
  output_names:
    system: "solute"
    nomad_workflow: "solute_generation.archive.yaml"
    states:
      generate: "gen_mol"
      minimize: "min"
      equilibrate: "equ"
  parameters:
    bond_length: 0.360
    bond_constant: 100000
    number_excl: 3

solvent_generation:
  relative_paths:
    workspaces: "solvent_generation"
    itp_files: "martini_v300"
    mdp_files: "solvent_generation/mdp_files"
  itp_files:
    particle_definition: "martini_v3.0.0.itp"
    solvents: "martini_v3.0.0_solvents_v1.itp"
  mdp_files:
    minimize: "min.mdp"
    equilibrate: "equ.mdp"
    production: "run.mdp"
  settings:
    n_threads: 1
    box_length: 5.0
  output_names:
    system: "solvent"
    nomad_workflow: "solvent_generation.archive.yaml"
    states:
      mol: "gen_mol"
      box: "gen_box"
      minimize: "minimize"
      equilibrate: "equilibrate"
      production: "production"

solute_solvation:
  relative_paths:
    workspaces: "solute_solvation"
    itp_files: "martini_v300"
    mdp_files: "solute_solvation/mdp_files"
  itp_files:
    particle_definition: "martini_v3.0.0.itp"
    solvents: "martini_v3.0.0_solvents_v1.itp"
  settings:
    n_threads: 1
  mdp_files:
    minimize: "min.mdp"
    equilibrate: "equ.mdp"
  output_names:
    system: "solute_solvent"
    nomad_workflow: "solute_solvation.archive.yaml"
    nomad_top_level_workflow: "full_workflow.solute_solvation.archive.yaml"
    states:
      generate: "gen"
      minimize: "min"
      equilibrate: "equ"

alchemical_transformation:
  relative_paths:
    workspaces: "alchemical_transformation"
    itp_files: "martini_v300"
    mdp_files: "alchemical_transformation/mdp_files"
  itp_files:
    particle_definition: "martini_v3.0.0.itp"
    solvents: "martini_v3.0.0_solvents_v1.itp"
  settings:
    n_threads: 2
    temperature: 300.
  mdp_files:
    production: "run_lambda.mdp"
  output_names:
    system: "alchemical_transformation"
    nomad_workflow: "alchemical_transformation.archive.yaml"
    nomad_top_level_workflow: "full_workflow.alchemical_transformation.archive.yaml"
    states:
      production: "production"

bilayer_generation:
  relative_paths:
    workspaces: "bilayer_generation"
    itp_files: "martini_v300"
    mdp_files: "bilayer_generation/mdp_files"
  itp_files:
    particle_definition: "martini_v3.0.0.itp"
    solvents: "martini_v3.0.0_solvents_v1.itp"
    phospholipids: "martini_v3.0.0_phospholipids_v1.itp"
  mdp_files:
    minimize: "min.mdp"
    equilibrate: "equ.mdp"
    production: "prod.mdp"
  settings:
    n_threads: 2
    box_length_xy: 10
    box_length_z: 7
    solvent:
      -
        name: W
        fraction: 1.0
  output_names:
    system: "bilayer"
    nomad_workflow: "bilayer_generation.archive.yaml"
    states:
      generate: "gen"
      minimize: "min"
      equilibrate: "equ"
      production: "prod"