target-version = "py39"
line-length = 120
fix = true
select = [
    "YTT",
    "S",
    "B",
    "A",
    "C4",
    "T10",
    "SIM",
    "I",
    "C90",
    "E", "W",
    "F",
    "PGH",
    "UP",
    "RUF",
    "TRY",
]
ignore = [
    "E501",
    "E731",
    "S101",
    "A003",
    "S324",
    "RUF012",
    "TRY003",
    "UP006",
    "UP035",
    "S311",
]

[per-file-ignores]
"tests/*" = ["S101"]
