# Configuration for Codecov
# Documentation: https://docs.codecov.com/docs/codecov-yaml

version: 2.0

# Common settings
comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # A coverage threshold that, if not met, will cause the check to fail
        target: 80%
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  # Ignore files or directories that you do not want to be included in coverage calculations
  - "tests/*"
  - "examples/*"
  - "docs/*"

# Adjust the notification settings based on your team's preferences
notifications:
  slack:
    url: "https://hooks.slack.com/services/your/slack/webhook"
    only_pulls: true

# Custom flags for different parts of the project
flags:
  backend:
    paths:
      - "src/backend"
  frontend:
    paths:
      - "src/frontend"
