site_name: martignac
repo_url: https://github.com/tbereau/martignac
site_url: https://tbereau.github.io/martignac
site_description: This is a template repository for Python projects that use Poetry for their dependency management.
site_author: Tristan Bereau
edit_uri: edit/main/docs/
repo_name: tbereau/martignac
copyright: Maintained by <a href="https://tristanbereau.com">Tristan Bereau</a>.

nav:
  - Home: index.md
  - Installation: install.md
  - Quick start: quickstart.md
  - Running workflows: running_workflows.md
  - Reference:
    - NOMAD:
      - nomad/datasets.md
      - nomad/entries.md
      - nomad/uploads.md
      - nomad/users.md
      - nomad/utils.md
      - nomad/workflows.md
    - Workflows:
      - workflows/solute_generation.md
      - workflows/solvent_generation.md
      - workflows/solute_in_solvent_generation.md
      - workflows/solute_in_solvent_alchemical.md
      - workflows/bilayer_generation.md
      - workflows/solute_in_bilayer_umbrella.md
    - Parsers:
      - parsers/gromacs_forcefields.md
      - parsers/gromacs_particle_definitions.md
      - parsers/gromacs_structures.md
      - parsers/gromacs_topologies.md
    - Liquid models:
      - liquid_models/mixtures.md
    - Utils:
      - utils/dashboard.md
      - utils/gromacs.md
      - utils/insane.md
      - utils/martini_flow_projects.md
      - utils/misc.md
      - utils/nomad.md
      - utils/packmol.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            loader: griffe

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tbereau/martignac
#    - icon: fontawesome/brands/python
#      link: https://pypi.org/project/martignac

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - md_in_html
