name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      NOMAD_USERNAME: ${{ secrets.NOMAD_USERNAME }}
      NOMAD_PASSWORD: ${{ secrets.NOMAD_PASSWORD }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libfftw3-dev libgsl0-dev
          sudo apt-get install -y libboost-all-dev libopenmpi-dev
          sudo apt-get install -y gromacs

      - name: Verify GROMACS installation
        run: |
          gmx --version
          echo "GROMACS has been installed successfully."

      - name: Install dependencies
        run: |
          pip install -r requirements.txt 
          pip install -r test_requirements.txt 
          pip install .

      - name: Run linting
        run: black --check .

      - name: Run tests
        run: pytest --color=yes --cov=martignac --cov-report=xml --cov-report=term-missing

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MkDocs and Dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python]

      - name: Build the documentation
        run: mkdocs build
